services:
  postgres:
    image: postgres:18-alpine
    container_name: express_boilerplate_postgres_dev
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:

