services:
  postgres:
    image: postgres:18.0-alpine3.22
    container_name: express_boilerplate_postgres_prod
    env_file:
      .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
